---
title: "Determining the activities and role of hydrogen utilizing microbes in the gut"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### I am interested in members of the microbial community at the final trophic level of the gut microbiome: sulfate reducers and methanogens. 
These community members play a crucial role in keeping fermentation reactions energetically favorable by removing hydrogen. I want to know whether host diet changes the metabolisms of these groups and to what extent these changes are occurring. In the cockroach hindgut, there are three groups of sulfate reducers that are active: *Frigididesulfovibrio*, *Desulfosarcina*, and an unclassified group of *Desulfobacterota*. There are two groups of methanogens in the cockroach gut, but I am specifically focused on *Methanimicrococcus*. Based on metatranscriptome data, I have determined that *Frigididesulfovibrio* and *Desulfosarcina* are doing sulfate reduction, and *Methanimicrococcus* is doing methanogenesis. There is a differentiation of alternative energy sources being used by the sulfate reducers, where *Frigididesulfovibrio* is using amino acids such as taurine and *Desulfosarcina* is using nitrate. However, it is difficult to determine what electron donors are being used from the metatranscriptome. I am going to use RNA-seq with pure cultures with known electron donors and acceptors to determine what these organisms are doing *in vivo*. This represents a novel use of *in vitro* culture work in combination with metatranscriptomes. I am also interested in how these sulfate reducers and methanogens can function together in the gut environment. Traditionally, these two groups are in competition for hydrogen and sulfate reducers can outcompete methanogens for this electron donor. This paradigm is not what we are seeing in the cockroach gut. To further address this question, I have utilized an inhibitor of methanogenesis to determine what affect this has on the microbial community as a whole and on the sulfate reducers specifically. Initial experiments have shown that the whole community is remaining stable, but sulfate reducers are increasing in abundance in response to the lack of methanogens. This suggests that the sulfate reducers are using hydrogen as an electron donor. Using the gnotobiotic *in vivo* model, we can determine what competition or cooperation is occurring between these groups. Sulfate reducers do not seem to colonize the gut alone, suggesting they rely on other members of the microbiome. Ongoing experiments are determining what these interactions are. My project is an analysis of one trophic level, but there are more trophic levels that need to be explored such as the primary and secondary degraders. 
